import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import BaseLayout from "@/layouts/BaseLayout";

const inter = Inter({
  subsets: ["vietnamese"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mobile Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <BaseLayout children={children} />
      </body>
    </html>
  );
}
